### ISSUE TITLE
Add runtime equivalence MVP for deploy, call, revert, log, and storage fixtures

### ISSUE THREAD

**Issue by arjunblj** [arjunblj/solar#1104]
Add a runtime differential test over the runtime-micro fixtures that executes Solar and solc bytecode in the same EVM backend and compares returns, reverts, logs, storage deltas, and gas class.

## Approach
Build after T09 so bytecode normalization and fixture identity are stable. Inspect whether the repo already has an EVM execution dependency or test helper under `crates/codegen/tests/`, `tools/tester/`, or existing dev-dependencies. If no Rust EVM backend is available and adding one would require editing locked manifests, use an existing external tool already required by PADS only if the test remains deterministic; otherwise produce an approval blocker.

The PR boundary is runtime equivalence MVP for a tiny corpus. For each fixture, compile with solc 0.8.31 and Solar using the same settings, deploy both bytecodes into the same backend state, run scripted calls, and compare return data, revert data, logs, storage writes, and gas class. Exact gas equality is not required for the MVP unless the compiler output is byte-for-byte equivalent; classify gas as same class or explicitly unsupported.

The design choice is to keep runtime scripts declarative and checked in while excluding traces, cache directories, and generated artifacts from git. The harness should fail with a readable diff that names fixture, call, expected solc outcome, Solar outcome, and the first divergent channel.

This issue avoids T09 by executing already-normalized bytecode rather than changing bytecode object comparison. It also does not implement new lowering or optimizer behavior. The first verifier is the runtime equivalence test filtered to the micro fixtures.

## Testing
- [ ] Runtime scripts cover at least one successful return, revert, log emission, and storage mutation fixture where Solar can emit bytecode.
- [ ] The same EVM backend and initial state are used for solc and Solar bytecode.
- [ ] Diff output reports return data, revert data, logs, storage deltas, and gas class separately.
- [ ] Generated traces, caches, out directories, and benchmark images are not committed.
- [ ] Unsupported fixtures are explicitly ledgered with reason and revisit condition.
- [ ] `SOLC_VERSION=0.8.31 cargo nextest run -p solar-compiler --test runtime_equivalence` passes or reports only checked-in unsupported entries.

Commands:
- `cargo check --workspace`
- `cargo clippy --workspace --all-targets -- -D warnings`

Rolls up to https://github.com/arjunblj/solar/issues/1034.

**Comment by arjunblj** [comment]
Closing as part of harness reset (cleanup --reset-project) before fresh canary.
